### ISSUE TITLE
Test content of tutorials

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tutorials#120] opened 2017-05-11 10:04 UTC
Travis can be set up to run cron jobs now, so I would be a useful thing to set up a test for the tutorials. E.g. @cdeil set something like this up for gammapy.

Obviously tutorials will broke with new versions, so maybe having a summary table of requirements/ list of conda envs where they supposed to be working is the way to go.

**Comment by adrn** [comment] 2017-09-21 21:01
duplicate of #32

**Closed by adrn** 2017-09-21 21:01 UTC
