### ISSUE TITLE
Add a prominent mention of the snippets and how they relate to the tutorials

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#107] opened 2016-03-24 01:30 UTC
When/if the snippets gallery in the astropy docs is merged, the astropy-tutorials front page should be updated to mention the snippets and describe what the distinction is between snippets and tutorials @adrn @kelle

**Comment by adrn** [comment] 2017-05-08 14:44
I think this is now a duplicate of astropy/astropy#6017?

**Closed by adrn** 2017-05-08 14:44 UTC
